import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/sections/NavBar';
import Footer from '@/components/sections/Footer';
import StairEffect from '@/components/StairEffect';
import PageTransition from '@/components/PageTransition';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StairEffect />
        <PageTransition>
          <NavBar />
          <div className="mt-[10vh] lg:mt-[100px]">{children}</div>
          <Footer />
        </PageTransition>
      </body>
    </html>
  );
}
